### ISSUE TITLE
Eder IO conduit + GregTech ItemType Filter

### ISSUE THREAD

**Issue by Sauruk** [JasonMcRay/InfiTech-1.7#385]
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at gregtech.common.tileentities.automation.GT_MetaTileEntity_TypeFilter.allowPutStack(GT_MetaTileEntity_TypeFilter.java:142)
	at gregtech.api.metatileentity.MetaTileEntity.func_102007_a(MetaTileEntity.java:536)
	at gregtech.api.metatileentity.BaseMetaTileEntity.func_102007_a(BaseMetaTileEntity.java:915)
	at com.enderio.core.common.util.ItemUtil.doInsertItemInv(ItemUtil.java:369)
	at com.enderio.core.common.util.ItemUtil.doInsertItemInv(ItemUtil.java:357)
	at com.enderio.core.common.util.ItemUtil.doInsertItem(ItemUtil.java:307)
	at crazypants.enderio.conduit.item.NetworkedInventory.insertItem(NetworkedInventory.java:284)
	at crazypants.enderio.conduit.item.NetworkedInventory.insertIntoTargets(NetworkedInventory.java:245)
	at crazypants.enderio.conduit.item.NetworkedInventory.doTransfer(NetworkedInventory.java:193)
	at crazypants.enderio.conduit.item.NetworkedInventory.transferItems(NetworkedInventory.java:166)
	at crazypants.enderio.conduit.item.NetworkedInventory.onTick(NetworkedInventory.java:113)
	at crazypants.enderio.conduit.item.ItemConduitNetwork.doNetworkTick(ItemConduitNetwork.java:214)
	at crazypants.enderio.conduit.ConduitNetworkTickHandler.tickEnd(ConduitNetworkTickHandler.java:63)
	at crazypants.enderio.conduit.ConduitNetworkTickHandler.onServerTick(ConduitNetworkTickHandler.java:47)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_377_ConduitNetworkTickHandler_onServerTick_ServerTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:247)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:590)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by Sauruk** [comment]
Maybe need to add. I use Ultra low voltage item type filter. After few seconds of work it provides server crush

**Comment by JasonMcRay** [comment]
Can you show a screenshot with configurations you use for all the blocks?

(@Blood-Asp would it be your issue or eIO?)

**Comment by JasonMcRay** [comment]
Oh actually i just crashed :D

**Comment by Blood-Asp** [comment]
Found the issue... now i wonder how to fix...

**Comment by JasonMcRay** [comment]
Oks... So I dont need to give you any more details, i guess :)

just FYI, happens in both 5.08.30 and 5.09.08

**Comment by Blood-Asp** [comment]
I just wonder why it never crashed while testing the latest change.

**Comment by JasonMcRay** [comment]
Well I am having eIo Item Conduits connected to Type Filter on my server and I haven't crashed yet.

**Comment by Blood-Asp** [comment]
Only happens when trying to insert items with certain oreDict tags.

**Comment by Blood-Asp** [comment]
https://www.dropbox.com/s/5du744jl2dy3ztf/gregtech_1.7.10-5.09.09-test2.jar?dl=0 Should work in this version.

**Comment by JasonMcRay** [comment]
Testing it.... Seems ok... Dont forget @Blood-Asp to port it to 5.08  :)

(also edited your comment to remove the link, just in case someone would be so keen on using that version in current versions of the pack.... I dont want to deal with that :D )

**Comment by Sauruk** [comment]
I catch a right moment before you delete the link. =) 
Works fine for me. Thank you for fast response

**Comment by Blood-Asp** [comment]
Tomorrow or latest sunday is release anyways. And shoud someone try to use the pyro oven in this version, the result will not be good... Also a few broken recipes.
