### ISSUE TITLE
Railcraft structures became not formed.

### ISSUE THREAD

**Issue by antkatcin** [JasonMcRay/InfiTech-1.7#419]
Sometimes when i come back from Nether my Iron tank and Steam turbine became not formed. To fix that i have to go to Nether and return back to Overworld. All of the structures don't cross chunk borders.

![2015-11-10_02 46 23](https://cloud.githubusercontent.com/assets/3091327/11145178/1aad648a-8a2d-11e5-8679-43ba71903389.png)

![2015-11-10_02 46 34](https://cloud.githubusercontent.com/assets/3091327/11145180/1faddbfe-8a2d-11e5-9a44-eb4314b623f2.png)

That log part probably can be related:
```
[17:21:01] [Client thread/INFO] [journeymap]: Mapping started in x:\Games\FTB\InfiTech2\minecraft\journeymap\data\sp\Bushi\DIM0. Memory: 2502MB total, 1021MB free 
[17:21:01] [Server thread/ERROR] [FML]: Exception caught during firing event ic2.api.energy.event.EnergyTileLoadEvent@50e29a:
java.lang.RuntimeException: Tile entity mods.railcraft.common.plugins.ic2.TileIC2MultiEmitterDelegate@36477fc1 must return at least 1 sub tile for IMetaDelegate.getSubTiles().
	at ic2.core.energy.Tile.<init>(Tile.java:28) ~[Tile.class:?]
	at ic2.core.energy.EnergyNetLocal.addTileEntity(EnergyNetLocal.java:101) ~[EnergyNetLocal.class:?]
	at ic2.core.energy.EnergyNetLocal.addTileEntity(EnergyNetLocal.java:66) ~[EnergyNetLocal.class:?]
	at ic2.core.energy.EventHandler.onEnergyTileLoad(EventHandler.java:28) ~[EventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_186_EventHandler_onEnergyTileLoad_EnergyTileLoadEvent.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) [EventBus.class:?]
	at mods.railcraft.common.plugins.ic2.IC2Plugin.addTileToNet(IC2Plugin.java:71) [IC2Plugin.class:?]
	at mods.railcraft.common.blocks.machine.alpha.TileSteamTurbine.addToNet(TileSteamTurbine.java:253) [TileSteamTurbine.class:?]
	at mods.railcraft.common.blocks.machine.alpha.TileSteamTurbine.func_145845_h(TileSteamTurbine.java:181) [TileSteamTurbine.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1939) [ahb.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489) [mt.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111) [bsx.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
[17:21:01] [Server thread/ERROR] [FML]: Index: 1 Listeners:
[17:21:01] [Server thread/ERROR] [FML]: 0: NORMAL
[17:21:01] [Server thread/ERROR] [FML]: 1: ASM: ic2.core.energy.EventHandler@5408df93 onEnergyTileLoad(Lic2/api/energy/event/EnergyTileLoadEvent;)V
[17:21:01] [Server thread/ERROR] [Railcraft]: IC2 API error, please update your mods. Error: java.lang.RuntimeException: Tile entity mods.railcraft.common.plugins.ic2.TileIC2MultiEmitterDelegate@36477fc1 must return at least 1 sub tile for IMetaDelegate.getSubTiles().
[17:21:01] [Server thread/ERROR] [Railcraft]: Tile entity mods.railcraft.common.plugins.ic2.TileIC2MultiEmitterDelegate@36477fc1 must return at least 1 sub tile for IMetaDelegate.getSubTiles().
[17:21:01] [Server thread/ERROR] [Railcraft]: ic2.core.energy.Tile.<init>(Tile.java:28)
[17:21:01] [Server thread/ERROR] [Railcraft]: ic2.core.energy.EnergyNetLocal.addTileEntity(EnergyNetLocal.java:101)
[17:21:01] [Server thread/ERROR] [Railcraft]: IC2 API error: EnergyTileLoadEvent is loaded from jar:file:/X:/Games/FTB/InfiTech2/minecraft/mods/industrialcraft-2-2.2.785-experimental.jar!/ic2/api/energy/event/EnergyTileLoadEvent.class
[17:21:01] [Server thread/ERROR] [FML]: Exception caught during firing event ic2.api.energy.event.EnergyTileLoadEvent@774c358b:
java.lang.RuntimeException: Tile entity mods.railcraft.common.plugins.ic2.TileIC2MultiEmitterDelegate@53596fde must return at least 1 sub tile for IMetaDelegate.getSubTiles().
	at ic2.core.energy.Tile.<init>(Tile.java:28) ~[Tile.class:?]
	at ic2.core.energy.EnergyNetLocal.addTileEntity(EnergyNetLocal.java:101) ~[EnergyNetLocal.class:?]
	at ic2.core.energy.EnergyNetLocal.addTileEntity(EnergyNetLocal.java:66) ~[EnergyNetLocal.class:?]
	at ic2.core.energy.EventHandler.onEnergyTileLoad(EventHandler.java:28) ~[EventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_186_EventHandler_onEnergyTileLoad_EnergyTileLoadEvent.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) [EventBus.class:?]
	at mods.railcraft.common.plugins.ic2.IC2Plugin.addTileToNet(IC2Plugin.java:71) [IC2Plugin.class:?]
	at mods.railcraft.common.blocks.machine.alpha.TileSteamTurbine.addToNet(TileSteamTurbine.java:253) [TileSteamTurbine.class:?]
	at mods.railcraft.common.blocks.machine.alpha.TileSteamTurbine.func_145845_h(TileSteamTurbine.java:181) [TileSteamTurbine.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1939) [ahb.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489) [mt.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111) [bsx.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
[17:21:01] [Server thread/ERROR] [FML]: Index: 1 Listeners:
[17:21:01] [Server thread/ERROR] [FML]: 0: NORMAL
[17:21:01] [Server thread/ERROR] [FML]: 1: ASM: ic2.core.energy.EventHandler@5408df93 onEnergyTileLoad(Lic2/api/energy/event/EnergyTileLoadEvent;)V
[17:21:01] [Server thread/ERROR] [Railcraft]: IC2 API error, please update your mods. Error: java.lang.RuntimeException: Tile entity mods.railcraft.common.plugins.ic2.TileIC2MultiEmitterDelegate@53596fde must return at least 1 sub tile for IMetaDelegate.getSubTiles().
[17:21:01] [Server thread/ERROR] [Railcraft]: Tile entity mods.railcraft.common.plugins.ic2.TileIC2MultiEmitterDelegate@53596fde must return at least 1 sub tile for IMetaDelegate.getSubTiles().
[17:21:01] [Server thread/ERROR] [Railcraft]: ic2.core.energy.Tile.<init>(Tile.java:28)
[17:21:01] [Server thread/ERROR] [Railcraft]: ic2.core.energy.EnergyNetLocal.addTileEntity(EnergyNetLocal.java:101)
[17:21:01] [Server thread/ERROR] [Railcraft]: IC2 API error: EnergyTileLoadEvent is loaded from jar:file:/X:/Games/FTB/InfiTech2/minecraft/mods/industrialcraft-2-2.2.785-experimental.jar!/ic2/api/energy/event/EnergyTileLoadEvent.class
[17:21:01] [Server thread/ERROR] [FML]: Exception caught during firing event ic2.api.energy.event.EnergyTileLoadEvent@1203646c:
java.lang.RuntimeException: Tile entity mods.railcraft.common.plugins.ic2.TileIC2MultiEmitterDelegate@6eea92de must return at least 1 sub tile for IMetaDelegate.getSubTiles().
	at ic2.core.energy.Tile.<init>(Tile.java:28) ~[Tile.class:?]
	at ic2.core.energy.EnergyNetLocal.addTileEntity(EnergyNetLocal.java:101) ~[EnergyNetLocal.class:?]
	at ic2.core.energy.EnergyNetLocal.addTileEntity(EnergyNetLocal.java:66) ~[EnergyNetLocal.class:?]
	at ic2.core.energy.EventHandler.onEnergyTileLoad(EventHandler.java:28) ~[EventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_186_EventHandler_onEnergyTileLoad_EnergyTileLoadEvent.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) [EventBus.class:?]
	at mods.railcraft.common.plugins.ic2.IC2Plugin.addTileToNet(IC2Plugin.java:71) [IC2Plugin.class:?]
	at mods.railcraft.common.blocks.machine.alpha.TileSteamTurbine.addToNet(TileSteamTurbine.java:253) [TileSteamTurbine.class:?]
	at mods.railcraft.common.blocks.machine.alpha.TileSteamTurbine.func_145845_h(TileSteamTurbine.java:181) [TileSteamTurbine.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1939) [ahb.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489) [mt.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111) [bsx.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
[17:21:01] [Server thread/ERROR] [FML]: Index: 1 Listeners:
[17:21:01] [Server thread/ERROR] [FML]: 0: NORMAL
[17:21:01] [Server thread/ERROR] [FML]: 1: ASM: ic2.core.energy.EventHandler@5408df93 onEnergyTileLoad(Lic2/api/energy/event/EnergyTileLoadEvent;)V
[17:21:01] [Server thread/ERROR] [Railcraft]: IC2 API error, please update your mods. Error: java.lang.RuntimeException: Tile entity mods.railcraft.common.plugins.ic2.TileIC2MultiEmitterDelegate@6eea92de must return at least 1 sub tile for IMetaDelegate.getSubTiles().
[17:21:01] [Server thread/ERROR] [Railcraft]: Tile entity mods.railcraft.common.plugins.ic2.TileIC2MultiEmitterDelegate@6eea92de must return at least 1 sub tile for IMetaDelegate.getSubTiles().
[17:21:01] [Server thread/ERROR] [Railcraft]: ic2.core.energy.Tile.<init>(Tile.java:28)
[17:21:01] [Server thread/ERROR] [Railcraft]: ic2.core.energy.EnergyNetLocal.addTileEntity(EnergyNetLocal.java:101)
[17:21:01] [Server thread/ERROR] [Railcraft]: IC2 API error: EnergyTileLoadEvent is loaded from jar:file:/X:/Games/FTB/InfiTech2/minecraft/mods/industrialcraft-2-2.2.785-experimental.jar!/ic2/api/energy/event/EnergyTileLoadEvent.class
[17:21:01] [Server thread/ERROR] [FML]: Exception caught during firing event ic2.api.energy.event.EnergyTileLoadEvent@1cca42dc:
java.lang.RuntimeException: Tile entity mods.railcraft.common.plugins.ic2.TileIC2MultiEmitterDelegate@abcde6d must return at least 1 sub tile for IMetaDelegate.getSubTiles().
	at ic2.core.energy.Tile.<init>(Tile.java:28) ~[Tile.class:?]
	at ic2.core.energy.EnergyNetLocal.addTileEntity(EnergyNetLocal.java:101) ~[EnergyNetLocal.class:?]
	at ic2.core.energy.EnergyNetLocal.addTileEntity(EnergyNetLocal.java:66) ~[EnergyNetLocal.class:?]
	at ic2.core.energy.EventHandler.onEnergyTileLoad(EventHandler.java:28) ~[EventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_186_EventHandler_onEnergyTileLoad_EnergyTileLoadEvent.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) [EventBus.class:?]
	at mods.railcraft.common.plugins.ic2.IC2Plugin.addTileToNet(IC2Plugin.java:71) [IC2Plugin.class:?]
	at mods.railcraft.common.blocks.machine.alpha.TileSteamTurbine.addToNet(TileSteamTurbine.java:253) [TileSteamTurbine.class:?]
	at mods.railcraft.common.blocks.machine.alpha.TileSteamTurbine.func_145845_h(TileSteamTurbine.java:181) [TileSteamTurbine.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1939) [ahb.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489) [mt.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111) [bsx.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
[17:21:01] [Server thread/ERROR] [FML]: Index: 1 Listeners:
[17:21:01] [Server thread/ERROR] [FML]: 0: NORMAL
[17:21:01] [Server thread/ERROR] [FML]: 1: ASM: ic2.core.energy.EventHandler@5408df93 onEnergyTileLoad(Lic2/api/energy/event/EnergyTileLoadEvent;)V
[17:21:01] [Server thread/ERROR] [Railcraft]: IC2 API error, please update your mods. Error: java.lang.RuntimeException: Tile entity mods.railcraft.common.plugins.ic2.TileIC2MultiEmitterDelegate@abcde6d must return at least 1 sub tile for IMetaDelegate.getSubTiles().
[17:21:01] [Server thread/ERROR] [Railcraft]: Tile entity mods.railcraft.common.plugins.ic2.TileIC2MultiEmitterDelegate@abcde6d must return at least 1 sub tile for IMetaDelegate.getSubTiles().
[17:21:01] [Server thread/ERROR] [Railcraft]: ic2.core.energy.Tile.<init>(Tile.java:28)
[17:21:01] [Server thread/ERROR] [Railcraft]: ic2.core.energy.EnergyNetLocal.addTileEntity(EnergyNetLocal.java:101)
[17:21:01] [Server thread/ERROR] [Railcraft]: IC2 API error: EnergyTileLoadEvent is loaded from jar:file:/X:/Games/FTB/InfiTech2/minecraft/mods/industrialcraft-2-2.2.785-experimental.jar!/ic2/api/energy/event/EnergyTileLoadEvent.class
```

**Comment by JasonMcRay** [comment]
Hmm... Never happend to me... Can you try (with backup of course) to update Railcraft to 9.8.0.0 and see if that will happen again? Thanks

http://www.railcraft.info/releases/

**Comment by antkatcin** [comment]
I did some more testing. Updating Railcraft (btw it require Computronics update) and ic2 didn't help. But i notice that looks (not 100% sure as a problem is not consistent) like problem happen only if i have powered Dimensional Anchor in Nether. After reading logs in a more detail i think this can be ic2 problem as Railcraft report some wired behaviour of ic2 api.

**Comment by JasonMcRay** [comment]
Will see what RC devs will have to say:

https://github.com/CovertJaguar/Railcraft/issues/730

**Comment by liach** [comment]
This error log is not the reason of the issue but the product of it. If the steam turbine is formed correctly then there will not be this type of runtime exception.

> But i notice that looks like problem happen only if i have powered Dimensional Anchor in Nether (not 100% sure as a problem is not consistent).

As a result it is likely a dimensional anchor mod bug. Test with only dim anchor, railcraft, and ic2 to see whether this issue exists. Then test without dim anchor.

**Comment by antkatcin** [comment]
I did some more testing. Issue reproducible only with a powered chunk loader in Nether, but not only with Dimensional Anchor. That can be World Anchor from Railcraft too.

Unfortunately i was not able to recreate the issue in a new clean world even with the same mods. So looks like this is a mod compatibility issue, but i still can't figure out of what mods.

Will try to do more testing.

**Comment by JasonMcRay** [comment]
Thanks. Can you please next time it happens pastebin.com the
fml-client.log? So I can give something to CovertJaguar?

2015-11-22 14:08 GMT+01:00 antkatcin <notifications@github.com>:
