### ISSUE TITLE
Client crash viewing Infusion Alter research.

### ISSUE THREAD

**Issue by Lithorn** [JasonMcRay/InfiTech-1.7#777]
#### Issue Description:
Also please state if you modified the modpack in any way.
Added Armor Status Hud mod, Tested with removed (Including core), still crashes client

#### Is the issue happening on server? Client? Both?
Client

#### What happens:
Research Infusion alter, click it inside Thaum book and crash

#### What you expected to happen:
View pattern for Infusion Alter containing Vinteum

#### Steps to reproduce (if aplicable):

1. Research Shard Re-Crystalization
2. Research Vinteum
3. Research Infusion alter and then attempt to view it
...

____
#### Modpack Version (Do *not* use "latest"):
3.2.13

#### Your most recent log file where the issue was present: 
---- Minecraft Crash Report ----
// Why did you do that?

Time: 10/12/16 1:50 AM
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at thaumcraft.client.gui.GuiResearchRecipe.drawArcaneCraftingPage(GuiResearchRecipe.java:779)
	at thaumcraft.client.gui.GuiResearchRecipe.drawPage(GuiResearchRecipe.java:364)
	at thaumcraft.client.gui.GuiResearchRecipe.genResearchBackground(GuiResearchRecipe.java:281)
	at thaumcraft.client.gui.GuiResearchRecipe.func_73863_a(GuiResearchRecipe.java:236)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1400)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

[pastebin/gist/pastee etc link here]
No need, culled unneeded info

**Comment by RabidDave** [comment]
Same for page 3 of void metal info on 3.2.13

**Comment by Lithorn** [comment]
Does this need a server update too or just client?
